// Code generated by "stringer -type NVType"; DO NOT EDIT.

package zfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeBoolean-1]
	_ = x[TypeByte-2]
	_ = x[TypeInt16-3]
	_ = x[TypeUint16-4]
	_ = x[TypeInt32-5]
	_ = x[TypeUint32-6]
	_ = x[TypeInt64-7]
	_ = x[TypeUint64-8]
	_ = x[TypeString-9]
	_ = x[TypeByteArray-10]
	_ = x[TypeInt16Array-11]
	_ = x[TypeUint16Array-12]
	_ = x[TypeInt32Array-13]
	_ = x[TypeUint32Array-14]
	_ = x[TypeInt64Array-15]
	_ = x[TypeUint64Array-16]
	_ = x[TypeStringArray-17]
	_ = x[TypeTime-18]
	_ = x[TypeNVList-19]
	_ = x[TypeNVListArray-20]
	_ = x[TypeBooleanValue-21]
	_ = x[TypeInt8-22]
	_ = x[TypeUint8-23]
	_ = x[TypeBooleanArray-24]
	_ = x[TypeInt8Array-25]
	_ = x[TypeUint8Array-26]
}

const _NVType_name = "TypeUnknownTypeBooleanTypeByteTypeInt16TypeUint16TypeInt32TypeUint32TypeInt64TypeUint64TypeStringTypeByteArrayTypeInt16ArrayTypeUint16ArrayTypeInt32ArrayTypeUint32ArrayTypeInt64ArrayTypeUint64ArrayTypeStringArrayTypeTimeTypeNVListTypeNVListArrayTypeBooleanValueTypeInt8TypeUint8TypeBooleanArrayTypeInt8ArrayTypeUint8Array"

var _NVType_index = [...]uint16{0, 11, 22, 30, 39, 49, 58, 68, 77, 87, 97, 110, 124, 139, 153, 168, 182, 197, 212, 220, 230, 245, 261, 269, 278, 294, 307, 321}

func (i NVType) String() string {
	if i >= NVType(len(_NVType_index)-1) {
		return "NVType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NVType_name[_NVType_index[i]:_NVType_index[i+1]]
}
