// Code generated by "stringer -type PoolStatus -trimprefix PoolStatus"; DO NOT EDIT.

package zfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PoolStatusCorruptCache-0]
	_ = x[PoolStatusMissingDevR-1]
	_ = x[PoolStatusMissingDevNr-2]
	_ = x[PoolStatusCorruptLabelR-3]
	_ = x[PoolStatusCorruptLabelNr-4]
	_ = x[PoolStatusBadGUIDSum-5]
	_ = x[PoolStatusCorruptPool-6]
	_ = x[PoolStatusCorruptData-7]
	_ = x[PoolStatusFailingDev-8]
	_ = x[PoolStatusVersionNewer-9]
	_ = x[PoolStatusHostidMismatch-10]
	_ = x[PoolStatusHosidActive-11]
	_ = x[PoolStatusHostidRequired-12]
	_ = x[PoolStatusIoFailureWait-13]
	_ = x[PoolStatusIoFailureContinue-14]
	_ = x[PoolStatusIOFailureMMP-15]
	_ = x[PoolStatusBadLog-16]
	_ = x[PoolStatusErrata-17]
	_ = x[PoolStatusUnsupFeatRead-18]
	_ = x[PoolStatusUnsupFeatWrite-19]
	_ = x[PoolStatusFaultedDevR-20]
	_ = x[PoolStatusFaultedDevNr-21]
	_ = x[PoolStatusVersionOlder-22]
	_ = x[PoolStatusFeatDisabled-23]
	_ = x[PoolStatusResilvering-24]
	_ = x[PoolStatusOfflineDev-25]
	_ = x[PoolStatusRemovedDev-26]
	_ = x[PoolStatusRebuilding-27]
	_ = x[PoolStatusRebuildScrub-28]
	_ = x[PoolStatusNonNativeAshift-29]
	_ = x[PoolStatusOk-30]
}

const _PoolStatus_name = "CorruptCacheMissingDevRMissingDevNrCorruptLabelRCorruptLabelNrBadGUIDSumCorruptPoolCorruptDataFailingDevVersionNewerHostidMismatchHosidActiveHostidRequiredIoFailureWaitIoFailureContinueIOFailureMMPBadLogErrataUnsupFeatReadUnsupFeatWriteFaultedDevRFaultedDevNrVersionOlderFeatDisabledResilveringOfflineDevRemovedDevRebuildingRebuildScrubNonNativeAshiftOk"

var _PoolStatus_index = [...]uint16{0, 12, 23, 35, 48, 62, 72, 83, 94, 104, 116, 130, 141, 155, 168, 185, 197, 203, 209, 222, 236, 247, 259, 271, 283, 294, 304, 314, 324, 336, 351, 353}

func (i PoolStatus) String() string {
	if i < 0 || i >= PoolStatus(len(_PoolStatus_index)-1) {
		return "PoolStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PoolStatus_name[_PoolStatus_index[i]:_PoolStatus_index[i+1]]
}
