{
 "title": "ZFS",
 "description": "Graphs ZFS ARC and ARC L2 Hit %, Hits, Misses, Size, and Zpool",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(zfs_pool_state{instance=\"$instance\"}, pool)"
    }
   },
   {
    "name": "interval",
    "query": "20s,30s,40s,1m,2m,5m,10m,30m,1h"
   },
   {
    "name": "rw_type",
    "label": "R/W Stat Level",
    "query": {
     "query": "label_values(zfs_pool_ops_total{instance=\"$instance\", pool=~\"$pool\"}, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pool status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pool",
   "targets": [
    {}
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_vdev_state{instance=~\"$instance\", pool=~\"$pool\", type=\"root\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Read-Only?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_readonly{instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Pool size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_size_bytes{instance=\"$instance\", pool=\"$pool\", type=\"root\"}"
    }
   ]
  },
  {
   "title": "Space used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - zfs_pool_free_bytes{instance=\"$instance\", pool=\"$pool\", type=\"root\"} / zfs_pool_size_bytes{instance=\"$instance\", pool=\"$pool\"}"
    }
   ]
  },
  {
   "title": "Scrub status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool_scrub_status{instance=\"$instance\", pool=\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time since scrub",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - zfs_pool_last_scrub_start_timestamp{instance=\"$instance\", pool=\"$pool\"}"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (type, device, parent) (zfs_pool_fragmentation_percent{instance=\"$instance\", pool=\"$pool\", type=\"raidz\"})"
    }
   ]
  },
  {
   "title": "Read errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zfs_pool_errors_total{instance=\"$instance\", pool=\"$pool\", errortype=\"read\", type=\"disk\"})"
    }
   ]
  },
  {
   "title": "Write errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zfs_pool_errors_total{instance=\"$instance\", pool=\"$pool\", errortype=\"write\", type=\"disk\"})"
    }
   ]
  },
  {
   "title": "Checksum errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zfs_pool_errors_total{instance=\"$instance\", pool=\"$pool\", errortype=\"checksum\", type=\"disk\"})"
    }
   ]
  },
  {
   "title": "Usage by dataset",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\"} >= 1024*1024*100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum without (name, type) (zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\"} < (1024*1024*100))",
     "legendFormat": "others"
    },
    {
     "expr": "max by (instance, pool) (zfs_pool_size_bytes{instance=\"$instance\", pool=~\"$pool\", type=\"root\"}) -\nsum by (instance, pool) (zfs_dataset_referenced_bytes{instance=~\"$instance\", pool=~\"$pool\"})",
     "legendFormat": "unused"
    },
    {
     "expr": "zfs_pool_size_bytes{instance=\"$instance\", pool=~\"$pool\", type=\"root\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Reads and Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "zpool reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(zfs_pool_ops_total{instance=~\"$instance\", pool=~\"$pool\", op=\"read\", type=~\"$rw_type\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ path }} {{ pool }}"
    }
   ]
  },
  {
   "title": "zpool writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(zfs_pool_ops_total{instance=~\"$instance\", pool=~\"$pool\", op=\"write\", type=~\"$rw_type\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ path }} {{ pool }}"
    }
   ]
  },
  {
   "title": "zpool read rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(zfs_pool_bytes_total{instance=~\"$instance\", pool=~\"$pool\", op=\"read\", type=~\"$rw_type\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ path }} {{ pool }}"
    }
   ]
  },
  {
   "title": "zpool write rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(zfs_pool_bytes_total{instance=~\"$instance\", pool=~\"$pool\", op=\"write\", type=~\"$rw_type\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ path }} {{ pool }}"
    }
   ]
  },
  {
   "title": "I/O utilisation by vdev",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (device) (\n  rate(node_disk_io_time_seconds_total[$interval]) \n  * on (instance, device) group_left(pool, parent)\n  count without() (\n    max by (instance, pool, parent, device) (\n      label_replace(zfs_pool_vdev_state{instance=~\"$instance\", pool=~\"$pool\", type=\"disk\"}, \"device\", \"$1\", \"path\", \"/dev/(.+)\")\n    )\n  )\n)",
     "legendFormat": "{{ instance }} - {{ pool }} {{ parent }}"
    }
   ]
  },
  {
   "title": "I/O utilisation by disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$interval]) \n* on (instance, device) group_left(pool, parent)\ncount without() (\n  max by (instance, pool, parent, device) (\n    label_replace(zfs_pool_vdev_state{instance=~\"$instance\", pool=~\"$pool\", type=\"disk\"}, \"device\", \"$1\", \"path\", \"/dev/(.+)\")\n  )\n)",
     "legendFormat": "{{ instance }} - {{ pool }} {{ parent }} {{ device }}"
    }
   ]
  },
  {
   "title": "ARC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ARC - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{instance=~\"$instance\"}[$interval]) /\n(rate(node_zfs_arc_demand_data_hits{instance=~\"$instance\"}[$interval]) + rate(node_zfs_arc_demand_data_misses{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "data"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{instance=~\"$instance\"}[$interval]) / (rate(node_zfs_arc_demand_metadata_hits{instance=~\"$instance\"}[$interval]) + rate(node_zfs_arc_demand_metadata_misses{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_demand_data_hits{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} data hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_hits{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} metadata hits"
    },
    {
     "expr": "rate(node_zfs_arc_demand_data_misses{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} data misses"
    },
    {
     "expr": "rate(node_zfs_arc_demand_metadata_misses{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} metadata misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} other"
    }
   ]
  },
  {
   "title": "ARC L2 - Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} asize"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} metadata"
    },
    {
     "expr": "node_zfs_arc_l2_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} size"
    }
   ]
  },
  {
   "title": "ARC L2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ARC L2 - Hit %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_l2_hits{instance=~\"$instance\"}[$interval]) / (rate(node_zfs_arc_l2_hits{instance=~\"$instance\"}[$interval]) + rate(node_zfs_arc_l2_misses{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{ instance }} L2"
    }
   ]
  },
  {
   "title": "ARC L2 - Hits, Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_l2_hits{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} hits"
    },
    {
     "expr": "rate(node_zfs_arc_l2_misses{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} misses"
    }
   ]
  }
 ]
}