---
kind: pipeline
type: docker
name: default

steps:
- name: docker build
  image: registry.spritsail.io/spritsail/docker-build
  pull: always

- name: docker publish
  image: registry.spritsail.io/spritsail/docker-publish
  pull: always
  settings:
    registry: registry.spritsail.io
    login: {from_secret: spritsail_login}
    repo: frebib/zfs-exporter
    tags: &tags
    - latest
    delete: no
  depends_on:
    - docker build
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: d436218dc12394b5b73b9f006cf021e81073f2e6b12bbb15a2e5f34d28146996

...
