// Code generated by "stringer -type PropertyType -trimprefix PropertyType"; DO NOT EDIT.

package zfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PropertyTypeNumber-0]
	_ = x[PropertyTypeString-1]
	_ = x[PropertyTypeIndex-2]
}

const _PropertyType_name = "NumberStringIndex"

var _PropertyType_index = [...]uint8{0, 6, 12, 17}

func (i PropertyType) String() string {
	if i < 0 || i >= PropertyType(len(_PropertyType_index)-1) {
		return "PropertyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PropertyType_name[_PropertyType_index[i]:_PropertyType_index[i+1]]
}
